spring:
  application:
    name: demo
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

server:
  compression:
    enabled: true
  shutdown: graceful
  port: 8080

logging:
  level:
    root: info
    org.springframework.web: debug
  structured:
    format:
      file: ecs
  file:
    name: application-log.json
